# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CSUP

on:
  schedule:
    - cron: '10 6 * * 0'  # Runs every Sunday at 6:10 AM UTC

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install imagemagick ghostscript exiftool gdal-bin python3-gdal
        pip install bs4 tqdm numpy regex urllib3 glob2 elementpath pypdf
    - name: Build CSUP 
      run: |
        python3 csup.py

    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: CSUP
        path: |
          AK_CSUP.zip
          PAC_CSUP.zip
          NW_CSUP.zip
          SW_CSUP.zip
          NC_CSUP.zip
          EC_CSUP.zip
          SC_CSUP.zip
          NE_CSUP.zip
          SE_CSUP.zip

    - name: SSH to mamba
      uses: appleboy/scp-action@v0.1.7
      with:
        host: apps4av.org
        username: apps4av
        password: ${{ secrets.MAMBA_PASSWORD }}
        port: 22
        source: "AK_CSUP.zip,PAC_CSUP.zip,NW_CSUP.zip,SW_CSUP.zip,NC_CSUP.zip,EC_CSUP.zip,SC_CSUP.zip,NE_CSUP.zip,SE_CSUP.zip"
        target: /home/apps4av/mamba.dreamhosters.com/new/staging
